import Head from 'next/head';

import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import requests from '../utils/requests';

//- Gets rendered on the client
export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header></Header>

      <Nav></Nav>

      <Results results={results.results} />
    </div>
  );
}

//- Gets rendered on the server, FIRST.  Before the client is rendered.
export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const results = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }}`
  )
    .then((res) => {
      if (!res.ok) {
        console.log('Failed', res.status, res.statusText);
        return {};
      }
      return res.json();
    })
    .catch((err) => {
      console.log('CATCH:', err);
    });

  return {
    props: { results },
  };
}
